// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhI2GT0pvU07USAbmRzHmwi1e9ay4IOt4',
    appId: '1:660704758185:web:55c4e6576a0fece0211cb8',
    messagingSenderId: '660704758185',
    projectId: 'sliet-hub',
    authDomain: 'sliet-hub.firebaseapp.com',
    storageBucket: 'sliet-hub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5hIdHe9rZWIr2vTgRrYElXv9E1XPEEbk',
    appId: '1:660704758185:android:a36e3b95eaca7163211cb8',
    messagingSenderId: '660704758185',
    projectId: 'sliet-hub',
    storageBucket: 'sliet-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC4-_9NXNaVf4Nvhw1XfOsudj_w85fbeo',
    appId: '1:660704758185:ios:841a382bdce162c9211cb8',
    messagingSenderId: '660704758185',
    projectId: 'sliet-hub',
    storageBucket: 'sliet-hub.firebasestorage.app',
    iosBundleId: 'com.example.slietHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC4-_9NXNaVf4Nvhw1XfOsudj_w85fbeo',
    appId: '1:660704758185:ios:841a382bdce162c9211cb8',
    messagingSenderId: '660704758185',
    projectId: 'sliet-hub',
    storageBucket: 'sliet-hub.firebasestorage.app',
    iosBundleId: 'com.example.slietHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhI2GT0pvU07USAbmRzHmwi1e9ay4IOt4',
    appId: '1:660704758185:web:442952e7c683eae2211cb8',
    messagingSenderId: '660704758185',
    projectId: 'sliet-hub',
    authDomain: 'sliet-hub.firebaseapp.com',
    storageBucket: 'sliet-hub.firebasestorage.app',
  );
}
